#!/bin/sh
[ "$ACTION" = ifup ] || exit 0
LOG_FILE="/tmp/log/UnblockNetease/unlock.log"
sleep 10
if [ "$(uci get UnblockNetease.@UnblockNetease[0].enable)" == "1" ]; then
    echo "$(date -R) restart app" >>"${LOG_FILE}"
    /etc/init.d/UnblockNetease restart
fi
